research_task:
  description: >
    Realize uma pesquisa completa sobre {topic}.
    Certifique-se de encontrar informações interessantes e relevantes considerando que o ano atual é 2024.
  expected_output: >
    Uma lista com 10 pontos principais das informações mais relevantes sobre {topic}.
  agent: researcher

fact_checking_task:
  description: >
    Verifique a precisão e veracidade das informações coletadas sobre {topic}.
    Identifique qualquer informação incorreta e confirme a autenticidade das fontes.
  expected_output: >
    Um resumo detalhado validando ou corrigindo as informações encontradas, com explicações para cada verificação e uma marcação das fontes mais confiáveis.
  agent: fact_checker

reporting_task:
  description: >
    Revise o contexto obtido e expanda cada tópico em uma seção completa para um relatório.
    Certifique-se de que o relatório seja detalhado e contenha informações relevantes validadas.
  expected_output: >
    Um relatório completo com os principais tópicos, cada um com uma seção de informação detalhada.
    O relatório deve estar em português PT-BR, formatado como texto embutido em HTML.
  agent: reporting_analyst
